src/api.rs
src/client.rs
src/main.rs

- Adds Server-Sent Events (SSE) support to stream cat
- CLI: New `--sse` flag for `cat` command
- API: Responds to `Accept: text/event-stream` header
- Streams full frame data in SSE format:
- event: topic
- id: frame id
- data: JSON-encoded full frame (including hash, but not the actual content)
- Enables real-time, push-based updates from server to client

feat: add Server-Sent Events support for stream cat

---

src/store.rs

Scru128s may include 0xFF
I was thinking of Scru128s as UTF-8 strings, but we use the direct byte encoding

fix: topic index encoding

---

src/store.rs

Because xs usage is generally rather light (when it comes to writes), we can probably get away with not spawning that many background threads.

tuning: use less (lsm) threads

---

docs/src/content/docs/getting-started/concepts.mdx
docs/src/content/docs/reference/architecture.mdx
docs/src/content/docs/reference/commands.mdx
docs/src/content/docs/reference/import-export.mdx
docs/src/content/docs/reference/supervisor-api.mdx
src/commands/mod.rs
src/commands/serve.rs
src/commands/tests.rs
src/lib.rs
src/main.rs

Commands provide a way to define reusable, stateless operations that:
- Execute on-demand with arguments and optional input
- Stream results via .recv events
- Can run multiple instances in parallel
- Handle errors independently per invocation
Unlike handlers (stateful) or generators (continuous), commands are designed for 
discrete, parallelizable tasks with immediate streaming output.

feat: add "commands": a mechanism for one-shot, streaming, parallelized operations

---

docs/src/content/docs/reference/generators.mdx
src/generators/serve.rs
src/generators/tests.rs

- unify generator scripts with handler/command config format
- support `return_options` and `duplex` in generator scripts
- document new generator configuration
- adjust generator tests

feat(generators): update generators to share handler and command configuration style

---

docs/src/content/docs/tutorials/threaded-conversations.mdx

- flesh out threaded conversation tutorial with additional turns
- show branching from two different messages and include mermaid chart

docs(tutorials): expand threaded conversations

---

src/generators/actor.rs
src/generators/generator.rs
src/generators/mod.rs
src/generators/serve.rs
src/generators/tests.rs

- implement new generator actor with self-termination logic
- simplify `serve` to just spawn and drop actors
- ensure jobs end on `.terminate` frames
- test termination and respawn behaviour

feat(generator): Extract and implement termination logic

---

examples/discord-bot/README.md
examples/x-macos-pasteboard/README.md
examples/x-macos-pasteboard/solid-ui/README.md

- update generator README examples to new `{run: {}}` format
- `git status --short`

docs(examples): update generator config format

---

src/generators/generator.rs

- ensure termination reason handled correctly
- `cargo t generators::tests::test_serve_terminate_respawn`

fix(generator): prioritize terminate events

---

docs/src/content/docs/reference/handlers.mdx

- document the required closure argument
- note `.registered` events and metadata
- mention that handlers ignore their own frames

docs(reference): clarify handler registration events

---

docs/src/content/docs/reference/commands.mdx

- clarify that return_options only affects `.recv` frames
- document context scoping for commands
- list built-in helper commands available inside `run` closures

docs(commands): clarify context and built-in helpers

---

docs/src/content/docs/reference/generators.mdx
src/generators/generator.rs
src/generators/serve.rs
src/generators/tests.rs

- document stop reason enum for generators
- restart generator pipelines automatically when they finish or error
- only remove generator loop after terminate
- test automatic restart behaviour
- `cd ./docs && npm run build`

feat(generators): restart pipeline on natural stop

---

src/generators/generator.rs
src/generators/serve.rs
src/generators/tests.rs

- emit `{topic}.stop` when spawning a generator fails
- ignore `.spawn.error` in the ServeLoop and evict on `.stop` with reason `spawn.error`
- adjust tests for the new stop frame

feat(generator): emit stop on spawn failure

---

Cargo.lock
Cargo.toml
src/main.rs

- embed xs.nu into binary via include_str!
- implement `xs nu` subcommand with --install/--clean options
- add `dirs` dependency

feat(nu): add embedded xs.nu management

---

src/main.rs

- use BTreeSet for unique clean targets
- add friendly abort messages for `nu --install` and `nu --clean`

fix(nu): dedup clean paths

---

docs/src/content/docs/reference/cli.mdx

- rewrite CLI reference with subcommand sections
- document each command's options with examples

docs(cli): expand command reference

---

docs/src/content/docs/reference/cli.mdx

- fix CLI documentation examples to use `./store` directory rather than `./store/sock`
- `cd ./docs && npm run build`

docs(cli): use store directory in examples

---

docs/src/content/docs/reference/generators.mdx
src/generators/generator.rs
src/generators/serve.rs
src/generators/tests.rs

- let running generator self-refresh when `.spawn` is received
- allow ServeLoop to ignore new spawns when generator is active
- document `update` stop reason and `update_id`

feat(generator): handle hot reload and docs

---

docs/src/content/docs/reference/generators.mdx
examples/x-macos-pasteboard/solid-ui/README.md

- mention `spawn.error` stop event in generator docs
- tweak clipboard example wording

docs(generator): document spawn error stop

---

README.md
docs/src/content/docs/getting-started/first-stream.mdx
docs/src/content/docs/getting-started/installation.mdx
xs.nu

- document `xs` CLI examples with explicit store path
- explain the fallback store used by `xs.nu`
- mention that the CLI still requires the path
- `cd ./docs && npm run build`

docs: clarify store defaults

---

docs/src/content/docs/reference/commands.mdx
src/commands/serve.rs
src/commands/tests.rs

- collect command pipeline output and emit a `.response` frame
- update docs for `.response` semantics
- adjust command tests for new behavior

feat(commands): emit single response frame

---

src/generators/generator.rs
src/generators/tests.rs
src/nu/engine.rs

- add `kill_job_by_name` helper to Engine
- name generator threads using spawn id
- terminate or reload only the matching generator thread
- test terminating one generator while another keeps running

feat(generator): kill job by spawn id

---

src/generators/generator.rs
src/generators/tests.rs
src/nu/engine.rs
src/store/mod.rs

- emit frames for each chunk of generator ByteStreams
- expose `cas_insert_bytes` helpers for raw CAS insertions
- add integration test covering ByteStream streaming via `ping`

feat(generator): stream byte chunks as events

---

docs/src/content/docs/reference/generators.mdx
docs/src/content/docs/reference/handlers.mdx
docs/src/content/docs/reference/store-api.mdx

- align TTL docs with implementation: ephemeral events are not stored
- document generator output streaming binary chunks
- `npm run build`

docs(reference): update ephemeral TTL and generator output

---

src/generators/serve.rs

- avoid respawning generators that were terminated before the startup threshold

fix(generator): skip restart after terminate

---

src/commands/serve.rs
src/commands/tests.rs

- use `PipelineData::into_value` when persisting command output
- store an empty array when command output is empty

fix(commands): use into_value for responses

---

docs/src/content/docs/reference/generators.mdx
src/generators/generator.rs
src/generators/mod.rs
src/generators/serve.rs
src/generators/tests.rs

- update generator runtime with Task struct and typed events
- emit parse errors instead of spawn errors
- adjust ServeLoop and docs for new protocol
- add unit test for emit_event helper

feat(generator): refactor runtime and protocol

---

docs/src/content/docs/reference/generators.mdx
src/generators/generator.rs
src/generators/serve.rs
src/generators/tests.rs

- emit shutdown event when the generator loop fully exits
- have ServeLoop evict generators based on `.shutdown`
- update generator docs with shutdown lifecycle event
- expect shutdown frames in tests

feat(generator): add shutdown lifecycle event

---

src/generators/generator.rs
src/generators/tests.rs

- refactor `emit_event` to accept primitive params
- update generator logic for new signature
- adjust unit tests

refactor(generator): simplify emit_event signature

---

docs/src/content/docs/getting-started/first-stream.mdx
docs/src/content/docs/reference/cli.mdx
src/main.rs
src/store/mod.rs
src/store/tests.rs
xs.nu

- support specifying a topic when reading streams
- add `--topic` CLI flag and nushell wrapper option
- implement topic filtering in the store using the topic index
- document new option and update tutorial examples
- test topic filtering

feat(cat): add topic filtering
